- blocks/article-feed/article-feed.css
- blocks/embed/embed.css
- blocks/featured-articles/featured-articles.css
- blocks/quote/quote.css
- blocks/search/search.css
- styles/styles.css
https://uncled-cls-fix--bamboohr-website--hlxsites.hlx.live/blog/
vs.
https://main--bamboohr-website--hlxsites.hlx.live/blog/
> chore: quick CLS improvement

- blog/blocks/featured-articles/featured-articles.js
- blog/scripts/scripts.js
- blog/styles/styles.css
https://uncled-color-by-category--bamboohr-website--hlxsites.hlx.page/blog/
vs.
https://main--bamboohr-website--hlxsites.hlx.page/blog/
> feat: color by category on homepage

- blog/blocks/table/table.css
https://uncled-table--bamboohr-website--hlxsites.hlx.page/blog/the-hr-pros-guide-to-thinking-like-a-marketer
vs.
https://main--bamboohr-website--hlxsites.hlx.page/blog/the-hr-pros-guide-to-thinking-like-a-marketer
> feat: basic table styling

- blog/blocks/article-feed/article-feed.css
- blog/blocks/article-header/article-header.css
- blog/blocks/article-header/article-header.js
- blog/blocks/featured-articles/featured-articles.css
- blog/blocks/featured-articles/featured-articles.js
https://main--bamboohr-website--hlxsites.hlx.live/blog/
vs. 
https://uncled-category-links--bamboohr-website--hlxsites.hlx.live/blog/
> feat: add category links

- blog/blocks/call-to-action/call-to-action.css
- blog/blocks/call-to-action/call-to-action.js
- blog/blocks/header/header.js
- blog/scripts/scripts.js
https://uncled-newsletter-modal--bamboohr-website--hlxsites.hlx.page/blog/
vs.
https://main--bamboohr-website--hlxsites.hlx.page/blog/
check the main CTA link...
> chore: newsletter modal

- blog/blocks/article-feed/article-feed.css
- blog/blocks/article-header/article-header.css
- blog/blocks/call-to-action/call-to-action.css
- blog/blocks/callout/callout.css
- blog/blocks/featured-articles/featured-articles.css
- blog/blocks/footer/footer.css
- blog/blocks/header/header.css
- blog/blocks/quote/quote.css
- blog/blocks/related-posts/related-posts.css
- blog/blocks/search/search.css
- blog/blocks/toc/toc.css
- blog/styles/styles.css
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/blog/
- After: https://mtian-style-updates--bamboohr-website--hlxsites.hlx.live/blog/
- After: https://mtian-style-updates--bamboohr-website--hlxsites.hlx.live/blog/burnout-prevention-tips-especially-for-hr
> mt revert breakpoints back

- blog/blocks/featured-articles/featured-articles.js
- blog/blocks/header/header.js
- blog/scripts/scripts.js
- blog/styles/styles.css
- test/scripts/scripts.test.js
https://uncled-post-breaking--bamboohr-website--hlxsites.hlx.live/blog/
vs.
https://main--bamboohr-website--hlxsites.hlx.live/blog/
there shouldn't be any visible differences here.
> chore: post breaking 202205 cleanup

- blog/blocks/footer/footer.js
- blog/scripts/delayed.js
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/blog/
- After: https://mtian-cookie-consent--bamboohr-website--hlxsites.hlx.live/blog/
> mt add trustArc

- blog/blocks/header/header.js
https://uncled-search-fix--bamboohr-website--hlxsites.hlx.live/
> chore: search fix

- blog/scripts/scripts.js
https://uncled-tbt-test--bamboohr-website--hlxsites.hlx.live/blog/
> chore: test tbt impact

- blog/scripts/scripts.js
- blog/styles/styles.css
https://uncled-lh-fix--bamboohr-website--hlxsites.hlx.live/blog/
> chore: lh fix

- blog/blocks/toc/toc.js
https://uncled-toc-no-numbers--bamboohr-website--hlxsites.hlx.page/blog/
vs. 
https://main--bamboohr-website--hlxsites.hlx.page/blog/
> chore: number supression

- blog/blocks/form/form.css
- blog/blocks/form/form.js
- tools/importer/helix-tools
form block
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/marketplace/suggest-an-app
- After: https://acapt-form--bamboohr-website--hlxsites.hlx.page/marketplace/suggest-an-app
> form block

- blog/scripts/scripts.js
https://main--bamboohr-website--hlxsites.hlx.page/hr-glossary/paid-time-off-pto
vs.
https://uncled-template-fix--bamboohr-website--hlxsites.hlx.page/hr-glossary/paid-time-off-pto
> fix: template naming

- tools/sidekick/config.json
We are planning to switch from JS to JSON format for the sidekick configuration in the near future. This PR is to prepare and ensure a smooth transition.
> chore(sidekick): prepare for new config format

- blog/blocks/app-cards/app-cards.css
- blog/blocks/listing/listing.css
- blog/blocks/listing/listing.js
- blog/blocks/search/search.css
- blog/scripts/scripts.js
partial solution for #33
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/applicant-tracking-systems
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/
- After: https://mtian-listing-block--bamboohr-website--hlxsites.hlx.live/marketplace/applicant-tracking-systems
- After: https://mtian-listing-block--bamboohr-website--hlxsites.hlx.live/marketplace/
> mt update listing block card and search cards style

- blog/blocks/listing/listing.js
- sort filter facetValues alphabetically
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/all-apps
- After: https://mtian-cleanup--bamboohr-website--hlxsites.hlx.page/marketplace/all-apps
> mt sort filter facetValues

- blog/blocks/listing/listing.js
- fix sort by newest
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/listing-category/applicant-tracking-systems
- After: https://mtian-cleanup--bamboohr-website--hlxsites.hlx.live/marketplace/listing-category/applicant-tracking-systems
> mt fix sort by newest on listing block

- blog/blocks/form/form.js
- use | to separate select options
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/suggest-an-app
- After: https://mtian-cleanup--bamboohr-website--hlxsites.hlx.live/marketplace/suggest-an-app
> mt use | to separate select options

- docs/style-guide/index.html
- docs/style-guide/style-guide.css
- create empty style guide
Test URLs:
- Before: none
- After: https://mtian-style-guide--bamboohr-website--hlxsites.hlx.live/docs/style-guide/index.html
> mt create empty style guide

- docs/style-guide/index.html
- docs/style-guide/style-guide.css
- import styles.css to style-guide
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/docs/style-guide/index.html
- After: https://mtian-style-guide--bamboohr-website--hlxsites.hlx.live/docs/style-guide/index.html
> mt import styles.css

- blog/blocks/form/form.js
- add entryDate to form submissions
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/suggest-an-app
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.live/marketplace/suggest-an-app
> mt add entry date to form submissions

- docs/style-guide/box-shadow.html
- docs/style-guide/style-guide.css
1. Adds box-shadow style guide page.
2. Adds styles for box-shadow style guide page.
ZZ-726
Test URLs:
- Before: none
- After: https://groberts-box-shadow-style-guide--bamboohr-website--hlxsites.hlx.page/docs/style-guide/box-shadow.html
> Box-shadow Style guide

- blog/blocks/form/form.js
Test URLs:
https://uncled-form-conditions--bamboohr-website--hlxsites.hlx.page/marketplace/request-information?show=broker
> chore: add form conditions

- blog/blocks/form/form.js
- sitemap-index.xml
- tools/fgrep/fgrep.js
https://uncled-fgrep-update--bamboohr-website--hlxsites.hlx.live/blog/
> chore: fgrep reconfig

- blog/scripts/scripts.js
https://uncled-fix-modal--bamboohr-website--hlxsites.hlx.page/blog/#
vs.
https://main--bamboohr-website--hlxsites.hlx.page/blog/#
> fix: modal regression

- blog/scripts/scripts.js
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/blog/introducing-bamboohr-employee-wellbeing
- After: https://uncled-figure-fix--bamboohr-website--hlxsites.hlx.page/blog/introducing-bamboohr-employee-wellbeing
> fix: replace firstChild by firstElementChild

- blog/blocks/form/form.css
- blog/blocks/form/form.js
- Add multi select option for forms.  see `Which partner(s) should reach out to this prospect? (Select all that apply)` field on send a lead form.
- add description option
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/send-a-lead
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.live/marketplace/send-a-lead
> mt add multi select input option

- blog/blocks/form/form.js
fix checkbox not getting value correctly when there are multiple checkboxes but only check one
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/send-a-lead
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.live/marketplace/send-a-lead
> mt fix checkbox not getting value correctly

- blog/scripts/scripts.js
- blog/styles/styles.css
add color theme class to body
change template name to resources-guides
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
- After: https://mtian-color-theme--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
> mt add color theme class to body

- blog/styles/styles.css
- h1, h2, h3, h4
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
- After: https://mtian-color-theme--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
> mt resources guides template titles

- blog/blocks/columns/columns.css
- blog/blocks/columns/columns.js
Adds styles for (cards) columns.
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
- After: https://groberts-card-block--bamboohr-website--hlxsites.hlx.page/resources/ebooks/expanded/compensation-strategy
> Adds card styles

- blog/styles/styles.css
- add secondary theme color variables
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/resources/guides/compensation-strategy
- After: https://mtian-color-theme--bamboohr-website--hlxsites.hlx.page/resources/guides/compensation-strategy
> mt add secondary theme color variables

- blog/blocks/carousel/carousel.css
- blog/blocks/carousel/carousel.js
- Mostly done, still needs some responsive tweaks and "watcher" for if slides are in view to update dot nav
- Finishing "Style 2" responsive styles and changing "mobile" design to happen at <=1024
- Couple stylelint fixes
- Adding "watcher" for slide event to change button states
Ticket: [ZZ-886](https://bamboohr.atlassian.net/browse/ZZ-886)
Doc: https://docs.google.com/document/d/1MyDnqtGt55bAI4e2-Pma2ZlEqjH_nBO3FrbvhlyBenU
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/carousel
- After: https://jwetmore-zz886-carousel--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/carousel
**Notes**
I applied the scroll event "watcher" to the existing Carousel code too, because I thought it made sense, but we could apply just to the new styles if anyone things …
> Carousel block

- blog/blocks/columns/columns.css
- Fix for the clickable link area for block Columns Small Icon
- Prettier fixes
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/marketplace/
- After: https://jgarrard-zz-982--bamboohr-website--hlxsites.hlx.page/marketplace/
> ZZ-982 Fix small icon columns clickable area

- blog/blocks/tabs/tabs.css
- blog/blocks/tabs/tabs.js
Ticket [ZZ-1056](https://bamboohr.atlassian.net/browse/ZZ-1056)
Doc: https://docs.google.com/document/d/1pGehsaruV-T63jIeEwlKjxHbVZRAqyEt1C_IdHpovNY
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/tabs
- After: https://jwetmore-zz1056-tabs-accordion--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/tabs
> Adding Accordion style to Tabs block

- blog/scripts/delayed.js
fix gtm id
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/marketplace/
- After: https://mtian-gtm--bamboohr-website--hlxsites.hlx.live/marketplace/
> mt fix gtm id

- blog/blocks/form/form.css
- blog/blocks/form/form.js
- blog/scripts/delayed.js
- blog/styles/styles.css
fix form modal doesn't work when there are multiple same form block
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/mtian/mkto-form
- https://main--bamboohr-website--hlxsites.hlx.page/pricing
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.page/drafts/mtian/mkto-form
- https://mtian-forms--bamboohr-website--hlxsites.hlx.page/pricing
> mt fix modal won't open when there is two duplicate form block

- blog/blocks/form/form.js
Get chilipiper timeout to work
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/mtian/mkto-form
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.page/drafts/mtian/mkto-form
> mt get chilipier work

- blog/blocks/form/form.css
- blog/blocks/form/form.js
add some media style for form
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/payroll-roi
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.page/payroll-roi
> mt add some media style for form

- blog/blocks/form/form.css
- blog/styles/styles.css
increase modal z-index.
fix form label alignment
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/pricing
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.page/pricing
> mt fix form label alignment and z-index

- blog/blocks/form/form.css
Increases z-index in case clearbit pushes form too far
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/payroll-roi
- After: https://groberts-form-z-index--bamboohr-website--hlxsites.hlx.page/payroll-roi
> Increases z-index in case clearbit pushes form too far

- blog/blocks/form/form.css
Override marketo form inline styles
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/payroll-roi
- After: https://mtian-forms--bamboohr-website--hlxsites.hlx.live/payroll-roi
> mt override mkto form inline style

- helix-sitemap.yaml
- sitemap-index.xml
Update marketplace sitemap path, this won't show up until we merge so I won't provide before and after urls
> mt update sitemap path

- blog/scripts/integrations-listing.js
fix request info link, breadcrumb links
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.live/integrations/listings/lattice
- After: https://mtian-marketplace--bamboohr-website--hlxsites.hlx.live/integrations/listings/lattice
> mt update links

- blog/styles/templates/payroll-roi.css
Switched out the form for a button for the modal so I updated some of the style to match.
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/lp/payroll-roi
- After: https://groberts-roi-style-updates--bamboohr-website--hlxsites.hlx.page/lp/payroll-roi
> Updates some styles for the roi page

- blog/blocks/meganav/meganav.js
- blog/scripts/scripts.js
https://uncled-meganav-img--bamboohr-website--hlxsites.hlx.live/?header=meganav
vs.
https://main--bamboohr-website--hlxsites.hlx.live/?header=meganav
> fix: meganav: make img relative to fetch source

- blog/blocks/quote/quote.css
- blog/blocks/quote/quote.js
Adds new quote styles for company name and secondary style for colors for company name and title.
Fix # zz 1119
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/quotes
- After: https://groberts-quote-company-style--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/quotes
> Adds quote styles

- blog/blocks/app-download/app-download.css
- blog/blocks/app-download/app-download.js
Added new block: App Download
- Block is color themable(block or page level) for titles and list bullets and background hexagons
- Block has 5 rows to be authored, with the last one for the main image that sits on top of the background hexagons
Test URLs:
https://jgarrard-zz-1120--bamboohr-website--hlxsites.hlx.page/drafts/jgarrard/app-download-test
> ZZ-1120 Created new App Download block

- .prettierignore
- .prettierrc.json
- package-lock.json
- package.json
add prettier and config files
Test URLs:
- https://jgarrard-eslint-prettier-update--bamboohr-website--hlxsites.hlx.page
> add prettier and project config files

- blog/scripts/scripts.js
quick fix for removing whitespace in title attribute on anchors with only images 
Test URLs:
- https://jgarrard-anchor-title-fix--bamboohr-website--hlxsites.hlx.page
> Fix for anchor with image only title

- blog/blocks/multi-element/multi-element.css
- blog/blocks/multi-element/multi-element.js
- Changed JS to move all "columns" inside main block
- Using `grid` only now to position columns
- Replacing JS `moveImages` to be grid styles
- Removed width block wrapper modifiers since new min-widths should work
Ticket [ZZ-1118](https://bamboohr.atlassian.net/browse/ZZ-1118)
Doc: https://docs.google.com/document/d/1ggtn-f-RijsAXwSjBUgguq3tAs8NCzkn8cCKoubU0FQ
Test URLs:
- Before: https://main--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/multi-element
- After: https://jwetmore-zz1118-multi-element--bamboohr-website--hlxsites.hlx.page/drafts/hoodoo/multi-element
> Mult-element updates

- fstab.yaml
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--bamboohr-website--bamboohr.hlx.page/blog/
- After: https://main--bamboohr-website--bamboohr.hlx.page/blog/
> Adding the new mountpoint to fstab

- fstab.yaml
Reverts hlxsites/bamboohr-website#204
> Revert "Adding the new mountpoint to fstab"
